services:
  app:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
      - ./credentials.json:/app/credentials.json
      - ./token.json:/app/token.json
      - ./database:/app/database/
      - ./archives:/app/archives
