target-version = "py310"
line-length = 88
src = ["src", "tests"]

exclude = [
    ".venv",
    "__pycache__",
    "archives",
]

[lint]
select = ["E", "F", "W", "I", "B"]

[format]
quote-style = "double"
